$testobject {

	$testcase 1 {
		$name ""
		$uuid "ecb7d54e-8483-47fa-8593-f71e67ccaf39"

		$teststep 1.1 {
			$name ""
			$uuid "5693f04d-fd07-43c1-ae7d-5dea807febb3"
			$inputs {
				timedur = 8
			}
			$outputs {
				distance = 137.6
				return inv_dist
			}
			$calltrace {
				*** Ignore Call Trace ***
			}
		}
	}

	$testcase 2 {
		$name ""
		$uuid "c4574655-c3ce-4eb6-ac21-9c28e73aec13"

		$teststep 2.1 {
			$name ""
			$uuid "23a12cb1-109e-47f5-9c96-abc4127a156c"
			$inputs {
				timedur = 9
			}
			$outputs {
				distance = 154.8
				return inv_dist
			}
			$calltrace {
				*** Ignore Call Trace ***
			}
		}
	}

	$testcase 3 {
		$name ""
		$uuid "af0af5f5-19a1-40fb-b172-49c72dd724f7"

		$teststep 3.1 {
			$name ""
			$uuid "ef0c146a-fb46-4c51-8f4f-c78ea4f88e3e"
			$inputs {
				timedur = 7
			}
			$outputs {
				distance = 120.4
				return inv_dist
			}
			$calltrace {
				*** Ignore Call Trace ***
			}
		}
	}

	$testcase 4 {
		$name ""
		$uuid "6542fb92-d700-4b60-86cb-ab0dfddf3386"

		$teststep 4.1 {
			$name ""
			$uuid "2f0ccaf3-6fc3-44bd-9344-eec99ebfedf0"
			$inputs {
				timedur = -2
			}
			$outputs {
				distance = 120.4
				return inv_time
			}
			$calltrace {
				*** Ignore Call Trace ***
			}
		}
	}

	$testcase 5 {
		$name ""
		$uuid "19e818cd-5e3a-4ee2-844d-189d97d7b6fd"

		$teststep 5.1 {
			$name ""
			$uuid "a16f79ee-cafa-49ab-86fa-09f38be114bb"
			$inputs {
				timedur = -1
			}
			$outputs {
				distance = 120.4
				return inv_time
			}
			$calltrace {
				*** Ignore Call Trace ***
			}
		}
	}

	$testcase 6 {
		$name ""
		$uuid "9e03dbba-24ee-4f85-ad41-e3ebb9c6f9c1"

		$teststep 6.1 {
			$name ""
			$uuid "034c8e3f-15e6-4853-9293-fe2f998c2eb6"
			$inputs {
				timedur = 0
			}
			$outputs {
				distance = 120.4
				return inv_time
			}
			$calltrace {
				*** Ignore Call Trace ***
			}
		}
	}

	$testcase 7 {
		$name ""
		$uuid "c0eea2d5-074b-4437-af04-ccaea5375511"

		$teststep 7.1 {
			$name ""
			$uuid "cf40a794-bdf3-4cfd-b9a6-460ff574f5ed"
			$inputs {
				timedur = 2
			}
			$outputs {
				distance = 34.4
				return obst_far
			}
			$calltrace {
				*** Ignore Call Trace ***
			}
		}
	}

	$testcase 8 {
		$name ""
		$uuid "ff9b798d-743d-4cc5-bdcc-965a21672387"

		$teststep 8.1 {
			$name ""
			$uuid "10d66880-e6a3-4281-8b28-b59c6b248c98"
			$inputs {
				timedur = 3
			}
			$outputs {
				distance = 51.6
				return obst_far
			}
			$calltrace {
				*** Ignore Call Trace ***
			}
		}
	}

	$testcase 9 {
		$name ""
		$uuid "14602935-689b-445d-851c-2c54e7e54607"

		$teststep 9.1 {
			$name ""
			$uuid "3d01f769-1462-48ff-a0f4-bb67637d2970"
			$inputs {
				timedur = 4
			}
			$outputs {
				distance = 68.8
				return obst_far
			}
			$calltrace {
				*** Ignore Call Trace ***
			}
		}
	}

	$testcase 10 {
		$name ""
		$uuid "175e3bc6-1f1e-4b39-859b-d2a5bddd7344"

		$teststep 10.1 {
			$name ""
			$uuid "d611893e-b47b-4534-a888-ac542fdd061e"
			$inputs {
				timedur = 0.12
			}
			$outputs {
				distance = 2.064
				return obst_near
			}
			$calltrace {
				*** Ignore Call Trace ***
			}
		}
	}

	$testcase 11 {
		$name ""
		$uuid "6aead056-86d4-4942-a8de-e0cd8eec64e3"

		$teststep 11.1 {
			$name ""
			$uuid "140ec76a-5584-43a0-a69f-88279d4e5463"
			$inputs {
				timedur = 0.18
			}
			$outputs {
				distance = 3.096
				return obst_near
			}
			$calltrace {
				*** Ignore Call Trace ***
			}
		}
	}

	$testcase 12 {
		$name ""
		$uuid "07cfaace-5dfe-4972-85b6-717394b59d2f"

		$teststep 12.1 {
			$name ""
			$uuid "451cac82-9c6e-4a63-a532-7c429bf3ecbd"
			$inputs {
				timedur = 0.23
			}
			$outputs {
				distance = 3.956
				return obst_near
			}
			$calltrace {
				*** Ignore Call Trace ***
			}
		}
	}
}