/*
 * Testdriver source generated by TESSY
 *
 * (c) Razorcat Development GmbH
 *
 * DO NOT EDIT THIS FILE !
 *
 *
 * File          : Slave Header (ts_vehdist_s.h)
 * Testpath      : C:/Users/Sowjanya/Projects/TESSY/REQ_MN~3/tessy\work\00000401\00000402\00000403\0000046F
 * Modulename    : New Module
 * Testobjectname: vehdist
 * Date          : 21.07.2020
 * Time          : 09:51:02
 * Tessy Version : 4.2.8
 *
 */

#if !defined (__TS_SLAVE_H)
   #define __TS_SLAVE_H


#endif /* !defined __TS_SLAVE_H */
